Q.6

In [ ]:
def cross_product(x, y, ans):
 
    cross_P.append(x[1] * y[2] - x[2] * y[1])
    cross_P.append(x[2] * y[0] - x[0] * y[2])
    cross_P.append(x[0] * y[1] - x[1] * y[0])

In [ ]:
# Driver function
if __name__ =='__main__':
    x = [4, 2, 2]
    y = [6, 5, 1]
    ans = []

    print("Cross product:", end =" ")
    crossProduct(x, y, ans)
 
# cross product of two vector array.
    for i in range(0, 3):
        print(cross_P[i], end =" ")

Cross product: -8 8 8 

Taking 8 common, therefore point of intersection is (-1,1,1).

Q.5

In [ ]:
import numpy as np
import cv2

In [ ]:
# M is the given matrix
M = np.array([-2872.0, 1744.3, -138.7, 77270.0, -273.9, -174.8, -3287.5, 94116.0, -0.7380, -0.6480, -0.1883, 75.633])
M = np.reshape(M, (3, 4))
print('M:\n', M)
M_normalized = M/M[2][3]
print('Normalized Matrix:\n', M_normalized)

K, R, t, *_ = cv2.decomposeProjectionMatrix(M_normalized)
t = -t[:3] / t[3]
print('\n', K, '\n')
print('\n', R, '\n')
print('\n', t, '\n')

M:
 [[-2.8720e+03  1.7443e+03 -1.3870e+02  7.7270e+04]
 [-2.7390e+02 -1.7480e+02 -3.2875e+03  9.4116e+04]
 [-7.3800e-01 -6.4800e-01 -1.8830e-01  7.5633e+01]]
Normalized Matrix:
 [[-3.79728425e+01  2.30626843e+01 -1.83385559e+00  1.02164399e+03]
 [-3.62143509e+00 -2.31116047e+00 -4.34664763e+01  1.24437745e+03]
 [-9.75764547e-03 -8.56768871e-03 -2.48965399e-03  1.00000000e+00]]

 [[ 4.23906196e+01 -4.61819386e-02  1.34246206e+01]
 [ 0.00000000e+00  4.18944605e+01  1.23549584e+01]
 [ 0.00000000e+00  0.00000000e+00  1.32217742e-02]] 


 [[-0.66192563  0.74941331  0.01530159]
 [ 0.13119877  0.13593284 -0.98199244]
 [-0.7379982  -0.64799842 -0.18829954]] 


 [[-54.95000876]
 [-47.8868527 ]
 [-21.50405194]] 

